
quarkus.http.host = 0.0.0.0
quarkus.http.port = 8081

quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/eshop_client
quarkus.datasource.username = root

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql = true

quarkus.rest-client.commande-service.url = http://localhost:8084/api

quarkus.http.auth.permission.api.paths = /api/*
quarkus.http.auth.permission.api.policy = authenticated
