

quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/eshop_stock?createDatabaseIfNotExist=true
quarkus.datasource.username = root
quarkus.datasource.password = root

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql = true


quarkus.http.port = 8083
quarkus.rest-client.produit-api.url=http://localhost:8082