quarkus.datasource.db-kind = mysql
quarkus.datasource.jdbc.url = jdbc:mysql://127.0.0.1:3306/eshop-produit?createDatabaseIfNotExist=true
quarkus.datasource.username = root
quarkus.datasource.password = root
quarkus.hibernate-orm.database.generation=update
quarkus.http.port = 8082